//! Config file writer.
//!
//! Serializes a [`ConfigDocument`] back to a string, preserving structure
//! for faithful roundtrip. Also provides Godot `FileAccess`-based file I/O.

use std::fmt::Write;

use godot::classes::file_access::ModeFlags;
use godot::classes::FileAccess;
use godot::prelude::*;

use super::types::{mapping_to_vim_command, ConfigDocument, ConfigLine};

/// Serialize a `ConfigDocument` to `.godot-vimrc` text. The output is
/// consumable by both `source_config_text()` (for the engine) and
/// `parse_config()` (for roundtrip fidelity).
pub(crate) fn serialize(doc: &ConfigDocument) -> String {
    let mut output = String::new();

    for line in &doc.lines {
        match line {
            ConfigLine::Comment(text) => {
                output.push_str(text);
                output.push('\n');
            }
            ConfigLine::BlankLine => {
                output.push('\n');
            }
            ConfigLine::Mapping(payload) => {
                // Emit preset marker before the mapping so parse_config()
                // can reconstruct preset metadata on re-read.
                if let Some(id) = &payload.preset_id {
                    let marker = if payload.enabled {
                        "enabled"
                    } else {
                        "disabled"
                    };
                    if id.is_empty() {
                        let _ = writeln!(output, "\" preset:{marker}");
                    } else {
                        let _ = writeln!(output, "\" preset:{marker} {id}");
                    }
                }
                let cmd = mapping_to_vim_command(&payload.parsed);
                if !payload.enabled {
                    if payload.preset_id.is_none() {
                        // User mappings use a self-contained `" disabled:` prefix
                        // (no separate marker line) for simpler roundtrip.
                        output.push_str("\" disabled: ");
                    } else {
                        // Presets already have a marker line above; just comment out.
                        output.push_str("\" ");
                    }
                }
                output.push_str(&cmd);
                output.push('\n');
            }
            ConfigLine::Setting(text) | ConfigLine::Leader(text) | ConfigLine::Other(text) => {
                output.push_str(text);
                output.push('\n');
            }
        }
    }

    output
}

/// Convenience wrapper: serialize then write. Currently unused (dialog goes
/// through `MappingService::to_text()` + `write_text_to_file`), but kept
/// for callers that have a `ConfigDocument` directly.
#[allow(dead_code)]
pub(crate) fn write_to_file(path: &str, doc: &ConfigDocument) -> Result<(), String> {
    let content = serialize(doc);
    write_text_to_file(path, &content)
}

/// Write pre-serialized config text to a file via Godot's `FileAccess`.
pub(crate) fn write_text_to_file(path: &str, content: &str) -> Result<(), String> {
    let gd_path = GString::from(path);

    let Some(mut file) = FileAccess::open(&gd_path, ModeFlags::WRITE) else {
        return Err(format!("Failed to open config file for writing: {path}"));
    };

    file.store_string(&GString::from(content));
    Ok(())
}

/// Read a config file via Godot's `FileAccess`. Returns `None` if the file
/// doesn't exist.
pub(crate) fn read_file(path: &str) -> Option<String> {
    let gd_path = GString::from(path);

    if !FileAccess::file_exists(&gd_path) {
        return None;
    }

    let file = FileAccess::open(&gd_path, ModeFlags::READ)?;
    Some(file.get_as_text().to_string())
}

/// Generate a fresh default config with header, leader, timeoutlen, and
/// all presets in their default enabled/disabled state.
pub(crate) fn generate_default_config(presets: &[super::presets::PresetDefinition]) -> String {
    let mut output = String::new();

    output.push_str("\" GodotVim Configuration\n");
    output.push_str("\" Generated by GodotVim. Manual edits are preserved.\n");
    output.push('\n');
    output.push_str("let mapleader = \" \"\n");
    let _ = writeln!(
        output,
        "set timeoutlen={}",
        crate::settings::defaults::TIMEOUTLEN
    );
    output.push('\n');
    output.push_str("\" --- User Mappings ---\n");
    output.push_str("\" Add your custom mappings below, e.g.:\n");
    output.push_str("\" nnoremap <Leader>w :save<CR>\n");
    output.push('\n');
    output.push_str("\" --- Presets (managed by Mapping Dialog) ---\n");

    for preset in presets {
        let marker = if preset.default_enabled {
            "enabled"
        } else {
            "disabled"
        };
        let _ = writeln!(output, "\" preset:{marker}");

        let cmd = preset.to_vim_command();
        if preset.default_enabled {
            output.push_str(&cmd);
        } else {
            output.push_str("\" ");
            output.push_str(&cmd);
        }
        output.push('\n');
    }

    output
}
